logging:
  config: classpath:log4j2.xml

server:
  servlet:
    context-path: /gRPCClient

spring:
  application:
    name: gRPCClient

  servlet:
    encoding:
      charset: UTF-8
      force: true

  grpc:
    client:
      channel:
        estoque:
          target: static://${GRPC_SERVER_IP:localhost}:${GRPC_SERVER_PORT:9017}

  web:
    error:
      include-stacktrace: never

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 9018

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 9028

---

spring:
  config:
    activate:
      on-profile: test